name: Create a pull request(PR) to update main on push
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update main
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update main branch
          title: Update main
          body: Credit new contributors by updating AUTHORS
          branch: main
